#!/usr/bin/env bash
set -eu

REPO_ROOT="$(git rev-parse --show-toplevel)"
CODEOWNERS_FILE="$REPO_ROOT/CODEOWNERS"

# Directories to exclude (not plugins)
EXCLUDED_DIRS=".git .github Bin"

# Get the GitHub repository from git remote
REPO_URL=$(git config --get remote.origin.url)
# Extract owner/repo from URL (handles both HTTPS and SSH)
GITHUB_REPO=$(echo "$REPO_URL" | sed -E 's|.*github\.com[:/]([^/]+/[^.]+)(\.git)?.*|\1|')

echo "Repository: $GITHUB_REPO"
echo ""

# Check if we have a GitHub token
if [[ -z "${GITHUB_TOKEN:-}" ]]; then
  echo "Warning: GITHUB_TOKEN not set. API requests will be rate-limited to 60/hour."
  echo ""
fi

# Load existing CODEOWNERS entries into a temp file for lookup
EXISTING_ENTRIES=$(mktemp)
trap "rm -f $EXISTING_ENTRIES" EXIT

if [[ -f "$CODEOWNERS_FILE" ]]; then
  grep -v '^#' "$CODEOWNERS_FILE" | grep -v '^$' > "$EXISTING_ENTRIES" || true
fi

# Function to get GitHub username using API
get_github_username() {
  local dir="$1"
  
  # Get the first commit SHA for this directory
  local commit_sha=$(git log --diff-filter=A --format='%H' --reverse -- "$dir" 2>/dev/null | head -n 1)
  
  if [[ -z "$commit_sha" ]]; then
    # Fallback: get the oldest commit
    commit_sha=$(git log --format='%H' --reverse -- "$dir" 2>/dev/null | head -n 1)
  fi
  
  if [[ -z "$commit_sha" ]]; then
    echo ""
    return
  fi
  
  # Query GitHub API for commit information
  local api_url="https://api.github.com/repos/$GITHUB_REPO/commits/$commit_sha"
  
  # Make API request with authentication if token is available
  local response
  local http_code
  if [[ -n "${GITHUB_TOKEN:-}" ]]; then
    response=$(curl -s -w "\n%{http_code}" -H "Authorization: token $GITHUB_TOKEN" \
                    -H "Accept: application/vnd.github.v3+json" \
                    "$api_url" 2>/dev/null || echo -e "\n000")
  else
    # Fall back to unauthenticated request (rate-limited to 60/hour)
    response=$(curl -s -w "\n%{http_code}" -H "Accept: application/vnd.github.v3+json" \
                    "$api_url" 2>/dev/null || echo -e "\n000")
  fi
  
  # Split response and http code
  http_code=$(echo "$response" | tail -n 1)
  response=$(echo "$response" | head -n -1)
  
  # Check if API request failed
  if [[ "$http_code" != "200" ]]; then
    echo ""
    return
  fi
  
  # Extract the GitHub username from author.login
  # Try Python JSON parsing first (most reliable)
  local github_username=""
  if command -v python3 &> /dev/null; then
    github_username=$(echo "$response" | python3 -c "import sys, json; data=json.load(sys.stdin); print(data.get('author', {}).get('login', '') if data.get('author') else '')" 2>/dev/null || echo "")
  fi
  
  if [[ -z "$github_username" ]]; then
    # Fallback to grep method
    github_username=$(echo "$response" | grep -o '"author"[^}]*"login":"[^"]*"' | grep -o '"login":"[^"]*"' | cut -d'"' -f4 | head -n 1)
  fi
  
  if [[ -n "$github_username" ]]; then
    echo "@$github_username"
  else
    echo ""
  fi
}

# Start building the CODEOWNERS file
cat > "$CODEOWNERS_FILE" <<'EOF'
# This file is auto-generated by the generate-codeowners workflow.
# Do not edit manually.
#
# Each plugin directory is owned by the first person who committed to it.
# Fallback owners: @Ly-sec @ItsLemmy

* @Ly-sec @ItsLemmy

EOF

# Iterate over top-level directories that are plugins
for dir in "$REPO_ROOT"/*/; do
  dir_name=$(basename "$dir")
  
  # Skip excluded directories
  case " $EXCLUDED_DIRS " in
    *" $dir_name "*) continue ;;
  esac
  
  pattern="/$dir_name/"
  
  # If this plugin already has an entry in CODEOWNERS, keep it as-is
  existing_line=$(grep "^${pattern} " "$EXISTING_ENTRIES" 2>/dev/null || true)
  if [[ -n "$existing_line" ]]; then
    echo "$existing_line" >> "$CODEOWNERS_FILE"
    echo "  [KEPT]  $existing_line"
    continue
  fi
  
  # Get the owner using GitHub API
  owner=$(get_github_username "$dir")
  
  # If we couldn't determine an owner, use the fallback
  if [[ -z "$owner" ]]; then
    owner="@Ly-sec @ItsLemmy"
    echo "  [FALLBACK] $pattern $owner (API lookup failed)"
  else
    echo "  [NEW]      $pattern $owner"
  fi
  
  echo "$pattern $owner" >> "$CODEOWNERS_FILE"
  
  # Small delay to avoid hitting rate limits
  sleep 0.1
done

echo ""
echo "CODEOWNERS file generated at $CODEOWNERS_FILE"